const DB=window.GL_DATA||{p:[],m:[],c:[]},P=DB.p||[],M=DB.m||[],C=DB.c||[],$=id=>document.getElementById(id),F=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n||0),PCT=n=>(Number.isFinite(n)?n:0).toFixed(1)+'%',E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const allProducts=[...new Set(P.map(x=>x[1]).filter(Boolean))].sort(),allZones=[...new Set(P.map(x=>x[2]).filter(Boolean))].sort(),months=['January','February','March','April','May','June','July','August'];
function sel(id,a,label,current=''){const e=$(id);e.innerHTML='<option value="">'+label+'</option>'+a.map(v=>'<option value="'+E(v)+'">'+E(v)+'</option>').join('');if(a.includes(current))e.value=current}
function refreshFilters(changed=''){const b=$('brand').value,z=$('zone').value;if(changed!=='brand'){const pvals=[...new Set(P.filter(x=>!z||x[2]===z).map(x=>x[1]).filter(Boolean))].sort();sel('brand',pvals,'All Products',b)}if(changed!=='zone'){const zvals=[...new Set(P.filter(x=>!b||x[1]===b).map(x=>x[2]).filter(Boolean))].sort();sel('zone',zvals,'All Zones',z)} }
sel('brand',allProducts,'All Products');sel('zone',allZones,'All Zones');['sku','state','month'].forEach((id,i)=>{sel(id,[],['All SKUs (YTD)','All States (YTD)','Jan–Aug YTD'][i]);$(id).disabled=true});
function rows(){const b=$('brand').value,z=$('zone').value;return P.filter(x=>(!b||x[1]===b)&&(!z||x[2]===z))}
function tot(a,y){return a.filter(x=>x[0]===y).reduce((t,x)=>{for(let i=3;i<9;i++)t[i-3]+=x[i]||0;return t},[0,0,0,0,0,0])}
function grp(a,i){const m={};a.forEach(x=>{const k=x[i]||'Unspecified',o=m[k]||(m[k]={name:k,a25:[0,0,0,0,0,0],a26:[0,0,0,0,0,0]}),q=x[0]===2026?o.a26:o.a25;for(let j=3;j<9;j++)q[j-3]+=x[j]||0});return Object.values(m).map(o=>{const a=o.a25,b=o.a26;return {...o,s25:a[0],s26:b[0],growth:a[0]?100*(b[0]-a[0])/a[0]:0,expire:b[3],expireRate:b[1]?100*b[3]/b[1]:0,bonusRate:b[4]?100*b[5]/b[4]:0,returnRate:b[1]?100*b[2]/b[1]:0}})}
function bars(id,a,key,p=false,n=12){a=[...a].sort((x,y)=>(y[key]||0)-(x[key]||0)).slice(0,n);const mx=Math.max(1,...a.map(x=>Math.abs(x[key]||0)));$(id).innerHTML=a.length?a.map(x=>`<div class="bar"><div class="name">${E(x.name)}</div><div class="track"><div class="fill" style="width:${Math.abs(x[key]||0)/mx*100}%"></div></div><div class="value">${p?PCT(x[key]):F(x[key])}</div></div>`).join(''):'<div class="note">No matching data</div>'}
function table(id,a,cols){$(id).innerHTML=a.length?a.map(x=>'<tr>'+cols.map(f=>'<td>'+f(x)+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="9">No matching data</td></tr>'}
function cust(){const z=$('zone').value,q=$('search').value.toLowerCase(),ri=z?8:6,di=z?9:7;const a=C.filter(x=>(!z||x[0]===z)&&(!q||String(x[1]).toLowerCase().includes(q)||String(x[0]).toLowerCase().includes(q)));return {g:a.filter(x=>x[ri]).sort((x,y)=>x[ri]-y[ri]),d:a.filter(x=>x[di]).sort((x,y)=>x[di]-y[di]),ri,di}}
function ctab(id,a,ri){$(id).innerHTML=a.length?a.map(x=>`<tr><td>${E(x[0])}</td><td>Portfolio</td><td>${x[ri]}</td><td>${E(x[1])}</td><td>${F(x[2])}</td><td>${F(x[3])}</td><td class="${x[4]>=0?'pos':'neg'}">${PCT(x[4])}</td><td class="${x[5]>=0?'pos':'neg'}">${F(x[5])}</td></tr>`).join(''):'<tr><td colspan="8">No matching data</td></tr>'}
function cbars(id,a){const b=a.slice(0,10).map(x=>({name:x[1],v:x[5]})),mx=Math.max(1,...b.map(x=>Math.abs(x.v)));$(id).innerHTML=b.length?b.map(x=>`<div class="bar"><div class="name">${E(x.name)}</div><div class="track"><div class="fill" style="width:${Math.abs(x.v)/mx*100}%"></div></div><div class="value">${F(x.v)}</div></div>`).join(''):'<div class="note">No matching data</div>'}
function trend(){const b=$('brand').value,z=$('zone').value,source=M.filter(x=>(!b||x[2]===b)&&(!z||!x[4]||x[4]===z));const a=months.map(m=>source.filter(x=>x[0]===2025&&x[1]===m).reduce((s,x)=>s+(x[3]||0),0)),c=months.map(m=>source.filter(x=>x[0]===2026&&x[1]===m).reduce((s,x)=>s+(x[3]||0),0)),mx=Math.max(1,...a,...c),xy=(v,i)=>[50+i*115,260-v/mx*220],line=v=>v.map((n,i)=>(i?'L':'M')+xy(n,i).join(',')).join(' ');$('trend').innerHTML=`<path d="${line(a)}" fill="none" stroke="#a855f7" stroke-width="4"/><path d="${line(c)}" fill="none" stroke="#31ecff" stroke-width="4"/>`+months.map((m,i)=>`<text x="${50+i*115}" y="290" class="axis" text-anchor="middle">${m.slice(0,3)}</text>`).join('')}
function render(){const a=rows(),t26=tot(a,2026),t25=tot(a,2025),zs=grp(a,2),ps=grp(a,1),growth=t25[0]?100*(t26[0]-t25[0])/t25[0]:0,top=[...zs].sort((x,y)=>y.s26-x.s26)[0],cc=cust(),b=$('brand').value,z=$('zone').value;
$('sales26').textContent=F(t26[0]);$('sales25').textContent='2025: '+F(t25[0]);$('growth').textContent=PCT(growth);$('growth').className=growth>=0?'pos':'neg';$('expire').textContent=F(t26[3]);$('expireRate').textContent=PCT(t26[1]?100*t26[3]/t26[1]:0)+' of Sold Amount';$('bonus').textContent=PCT(t26[4]?100*t26[5]/t26[4]:0);$('bonusQty').textContent=F(t26[5])+' bonus qty';$('returnRate').textContent=PCT(t26[1]?100*t26[2]/t26[1]:0);$('returnValue').textContent=F(t26[2])+' returned';$('topZone').textContent=top?top.name:'—';$('topShare').textContent=PCT(top&&t26[0]?100*top.s26/t26[0]:0)+' share';$('growCount').textContent=cc.g.length;$('declineCount').textContent=cc.d.length;
bars('compare',zs,'s26');bars('growthBars',zs,'growth',true);bars('expireZone',zs,'expire');bars('expireZone2',zs,'expire');bars('productSales',ps,'s26');bars('productGrowth',ps,'growth',true);bars('expireProduct',ps,'expire');bars('expireProduct2',ps,'expire');bars('bonusProduct',ps,'bonusRate',true);bars('bonusProduct2',ps,'bonusRate',true);bars('bonusZone',zs,'bonusRate',true);
table('zoneBody',zs,[x=>E(x.name),x=>F(x.s26),x=>F(x.s25),x=>PCT(t26[0]?100*x.s26/t26[0]:0),x=>PCT(x.growth),x=>F(x.expire),x=>PCT(x.expireRate),x=>PCT(x.bonusRate),x=>PCT(x.returnRate)]);table('productBody',ps,[x=>E(x.name),x=>F(x.s26),x=>F(x.s25),x=>PCT(x.growth),x=>F(x.expire),x=>PCT(x.expireRate),x=>PCT(x.bonusRate),x=>PCT(x.returnRate)]);ctab('growthTable',cc.g,cc.ri);ctab('declineTable',cc.d,cc.di);cbars('growBars',cc.g);cbars('declineBars',cc.d);
$('donutTotal').textContent=F(t26[0]);$('legend').innerHTML=zs.sort((x,y)=>y.s26-x.s26).map(x=>`<div class="legendItem"><span>${E(x.name)}</span><strong>${PCT(t26[0]?100*x.s26/t26[0]:0)}</strong></div>`).join('');$('smart').innerHTML=`<div class="smartCard"><span>Active Product</span><strong>${E(b||'All Products')}</strong><small>All KPIs & charts filtered</small></div><div class="smartCard"><span>Active Zone</span><strong>${E(z||'All Zones')}</strong><small>Cross-filter enabled</small></div><div class="smartCard"><span>YTD Growth</span><strong class="${growth>=0?'pos':'neg'}">${PCT(growth)}</strong><small>Jan–Aug 2026 vs 2025</small></div><div class="smartCard"><span>Top Zone</span><strong>${top?E(top.name):'—'}</strong><small>${PCT(top&&t26[0]?100*top.s26/t26[0]:0)} share</small></div>`;trend()}
$('brand').onchange=()=>{refreshFilters('brand');render()};$('zone').onchange=()=>{refreshFilters('zone');render()};$('search').oninput=render;$('resetBtn').onclick=()=>{$('brand').value='';$('zone').value='';$('search').value='';refreshFilters();render()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view).classList.add('active')});$('langBtn').onclick=()=>{};render();